Init:
  unstash: []
  stashes:
    - name: "source"
      includes: "**/*"
      excludes: ".pipeline/**"
    - name: "application"
      includes: "**/*"

'Pull-Request Voting':
  unstash:
    - source
  stashes: []

Build:
  unstash:
    - source
  stashes: []

Integration:
  unstash:
    - source
    - buildResult
  stashes: []

Acceptance:
  unstash:
    - buildDescriptor
    - buildResult
    - deployDescriptor
  stashes: []

#Compliance:
#  unstash:
#    - application
#  stashes: []

Performance:
  unstash:
    - source
    - buildResult
  stashes: []

Release:
  unstash:
    - buildDescriptor
    - buildResult
    - deployDescriptor
  stashes: []
